#ST7565_ENABLE = yes
#WPM_ENABLE = yes
SEND_STRING_ENABLE = yes
VIA_ENABLE = yes
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
OLED_ENABLE = no
LTO_ENABLE = yes
TAPDANCE_ENABLE = no
# Reduce firmware size
NO_DEBUG = yes
NO_PRINT = yes
NO_CONSOLE = yes
NO_COMMAND = yes

# Remove actions
NO_ACTION_LAYER = yes
NO_ACTION_ONESHOT = yes
NO_ACTION_MACRO = yes
NO_ACTION_FUNCTION = yes
NO_ACTION_TAPPING = yes

# Disable optional features 
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
UNICODE_ENABLE = no